version: "3.7"

services:
  server:
    image: hedgepay/obsidian:latest
    user: "1000:1000"
    init: true
    volumes:
      - ./vault:/vault
    ports:
      - "8080:8080"
    restart: unless-stopped
