version: "3.7"

services:
  server:
    image: hedgepay/obsidian:latest
    user: "1000:1000"
    init: true
    volumes:
      - ./vault:/vault
    ports:
      - "8080:8080"
    restart: unless-stopped

  app_proxy:
    image: getumbrel/app-proxy:1.0.0
    environment:
      APP_HOST: server
      APP_PORT: 8080
    depends_on:
      - server
    ports:
      - "8080:8080"
